language: node_js

node_js:
- '4'

before_script:
  - npm install -g codeclimate-test-reporter

script:
  - npm run lint
  - npm run coverage

after_script:
  - codeclimate-test-reporter < coverage/lcov.info
